server:
  port: 8080
  mode: debug

database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: thinking_map
  sslmode: disable
redis:
  addr: ${REDIS_ADDR}
  password: ${REDIS_PASSWORD}

jwt:
  secret: your-secret-key
  expire: 24h

log:
  level: info
  filename: logs/app.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true
  console: true 