server:
  port: 8080
  mode: debug

database:
  driver: postgres
  host: ${DB_HOST}
  port: ${DB_PORT}
  username: ${DB_USERNAME}
  password: ${DB_PASSWORD}
  dbname: thinking_map
  sslmode: disable
redis:
  addr: ${REDIS_ADDR}
  password: ${REDIS_PASSWORD}

jwt:
  secret: your-secret-key
  expire: 24h


llm:
  openai:
    api_key: ${OPENAI_API_KEY}
    base_url: ${OPENAI_BASE_URL}
    model: ${OPENAI_MODEL}
    timeout: 300s
  deepseek:
    api_key: ${DEEPSEEK_API_KEY}
    model: ${DEEPSEEK_MODEL}
    timeout: 300s
  claude:
    api_key: ${CLAUDE_API_KEY}
    model: ${CLAUDE_MODEL}
    timeout: 300s

sse:
  ping_interval: 15s  # 心跳包间隔
  client_timeout: 60s  # 客户端超时时间 

log:
  level: info
  filename: logs/app.log
  maxSize: 100
  maxBackups: 10
  maxAge: 30
  compress: true
  console: true 