-- 数据库初始化脚本
-- 注意：此脚本仅在 PostgreSQL 容器首次启动时执行

CREATE TABLE IF NOT EXISTS users (
    serial_id SERIAL NOT NULL,
    id uuid NOT NULL,
    username varchar(32) NOT NULL,
    email varchar(255) NOT NULL,
    password varchar(255) NOT NULL,
    full_name varchar(100) NOT NULL,
    status smallint NOT NULL DEFAULT 1,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    PRIMARY KEY (serial_id)
);

CREATE UNIQUE INDEX users_id_key ON public.users USING btree (id);

CREATE UNIQUE INDEX users_username_key ON public.users USING btree (username);

CREATE UNIQUE INDEX users_email_key ON public.users USING btree (email);

CREATE INDEX idx_users_deleted_at ON public.users USING btree (deleted_at);

CREATE TABLE IF NOT EXISTS messages (
    serial_id SERIAL NOT NULL,
    id uuid NOT NULL,
    parent_id uuid,
    conversation_id uuid,
    user_id uuid,
    message_type varchar(20) NOT NULL DEFAULT 'text'::character varying,
    role varchar(48),
    content jsonb NOT NULL,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    PRIMARY KEY (serial_id)
);

CREATE UNIQUE INDEX messages_id_key ON public.messages USING btree (id);

CREATE INDEX idx_messages_parent_id ON public.messages USING btree (parent_id);

CREATE INDEX idx_messages_chat_id ON public.messages USING btree (conversation_id);

CREATE INDEX idx_messages_deleted_at ON public.messages USING btree (deleted_at);

CREATE TABLE IF NOT EXISTS thinking_maps (
    serial_id SERIAL NOT NULL,
    id uuid NOT NULL,
    user_id uuid NOT NULL,
    title varchar(255),
    problem text NOT NULL,
    problem_type varchar(50),
    target text,
    key_points jsonb,
    constraints jsonb,
    conclusion text,
    status varchar(16) NOT NULL DEFAULT 'initial'::character varying,
    metadata jsonb,
    created_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone NOT NULL DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    PRIMARY KEY (serial_id)
);

CREATE UNIQUE INDEX thinking_maps_id_key ON public.thinking_maps USING btree (id);

CREATE INDEX idx_thinking_maps_user_id ON public.thinking_maps USING btree (user_id);

CREATE INDEX idx_thinking_maps_deleted_at ON public.thinking_maps USING btree (deleted_at);

CREATE TABLE IF NOT EXISTS thinking_nodes (
    serial_id SERIAL NOT NULL,
    id uuid NOT NULL,
    map_id uuid NOT NULL,
    parent_id uuid,
    node_type varchar(50) NOT NULL,
    question text NOT NULL,
    target text,
    context jsonb DEFAULT '{}'::jsonb,
    decomposition jsonb DEFAULT '{}'::jsonb,
    conclusion jsonb DEFAULT '{}'::jsonb,
    status varchar(16) DEFAULT 'initial'::character varying,
    position jsonb DEFAULT '{"x": 0, "y": 0}'::jsonb,
    metadata jsonb DEFAULT '{}'::jsonb,
    dependencies jsonb DEFAULT '[]'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    PRIMARY KEY (serial_id)
);

CREATE UNIQUE INDEX thinking_nodes_id_key ON public.thinking_nodes USING btree (id);

CREATE INDEX idx_thinking_nodes_map_id ON public.thinking_nodes USING btree (map_id);

CREATE INDEX idx_thinking_nodes_parent_id ON public.thinking_nodes USING btree (parent_id);

CREATE INDEX idx_thinking_nodes_deleted_at ON public.thinking_nodes USING btree (deleted_at);

-- ----------------------------
-- Table structure for rag_records
-- ----------------------------
-- Generated by the database client.
CREATE TABLE rag_records(
    serial_id SERIAL NOT NULL,
    id uuid NOT NULL,
    query text NOT NULL,
    answer text NOT NULL,
    sources varchar(128) NOT NULL,
    results jsonb DEFAULT '[]'::jsonb,
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    updated_at timestamp without time zone DEFAULT CURRENT_TIMESTAMP,
    deleted_at timestamp without time zone,
    PRIMARY KEY(serial_id)
);
CREATE UNIQUE INDEX rag_records_id_key ON public.rag_records USING btree (id);
CREATE INDEX idx_rag_records_deleted_at ON public.rag_records USING btree (deleted_at);